{
 "title": "Kepler Power Monitor",
 "description": "Dashboard for Power Monitor",
 "tags": [ "power-monitor-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kepler_node_package_joules_total{job=\"$job\"}, instance)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(kepler_node_package_joules_total{job=\"$job\"}, mode)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kepler_container_joules_total{job=\"$job\"}, container_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_joules_total{job=\"$job\", container_namespace=~\"$namespace\"},pod_name)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kepler_container_joules_total,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(kepler_node_package_joules_total{job=~\"$job\", mode=~\"$zone\"}[5m]))"
    }
   ]
  },
  {
   "title": "Current Active Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(kepler_node_core_joules_total{job=~\"$job\", mode=~\"$zone\"}[5m]))"
    }
   ]
  },
  {
   "title": "Current Idle Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(kepler_node_uncore_joules_total{job=~\"$job\", mode=~\"$zone\"}[5m]))"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by (instance, source)(kepler_node_info{job=~\"$job\"})"
    }
   ]
  },
  { "title": "RAPL Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "RAPL Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "group by (instance,mode)(kepler_node_package_joules_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Power Consumption (W) per Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(kepler_node_package_joules_total{job=~\"$job\", mode=~\"$zone\"}[5m]))",
     "legendFormat": "Zone - {{zone}}"
    }
   ]
  },
  {
   "title": "Node Power Consumption (W) By Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(kepler_node_package_joules_total{job=~\"$job\", instance=~\"$node\", mode=~\"$zone\"}[5m])",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Active Power Consumption (W) By Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(kepler_node_core_joules_total{job=~\"$job\", instance=~\"$node\", mode=~\"$zone\"}[5m])",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Idle Power Consumption (W) By Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(kepler_node_uncore_joules_total{job=~\"$job\", instance=~\"$node\", mode=~\"$zone\"}[5m])",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  { "title": "Power Monitor - Namespace Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Top 10 Power Consuming Namespaces (W) per Zone",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(10,sum by (container_namespace,mode)(rate(kepler_container_joules_total{job=~\"$job\", mode=~\"$zone\"}[5m])))"
    }
   ]
  },
  {
   "title": "Total Power Consumption of Pods in Namespace (W) per Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(kepler_container_joules_total{job=~\"$job\", container_namespace=~\"$namespace\", mode=~\"$zone\"}[5m]))",
     "legendFormat": "Zone - {{zone}}"
    }
   ]
  },
  {
   "title": "Pod Power Consumption (W) By Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(kepler_container_joules_total{job=~\"$job\", container_namespace=~\"$namespace\", pod_name=~\"$pod\", mode=~\"$zone\"}[5m])",
     "legendFormat": "{{zone}} - {{pod_name}}"
    }
   ]
  }
 ]
}